src/ConfigR/Scripting/ScriptConfigLoader.cs
src/test/ConfigR.Features/LocalConfigurationFeature.cs

fix script execution failure log messages

---

src/ConfigR/ConfigExtensions.cs
src/ConfigR/Scripting/ConfigRScriptHost.cs
src/ConfigR/Scripting/IConfigRScriptHost.cs

removed all code tagged with [Obsolete] and mentioning 0.9.0
https://github.com/config-r/config-r/issues/192

fixed: Remove obsolete members #192

---

src/ConfigR.ruleset

refactor: fix ruleset

---

src/ConfigR/Properties/AssemblyInfo.cs

increment to 0.14.0

---

src/ConfigR/BasicConfig.cs
src/ConfigR/ConfigR.csproj
src/ConfigR/ObjectExtensions.cs
src/ConfigR/packages.config

Removed dependency on Json.NET

---

src/ConfigR/Scripting/ScriptConfigLoader.cs

update hack comment and exception message for no-op scripts

---

src/ConfigR.Dictionary
src/test/ConfigR.Testing.Service/Program.cs
src/test/ConfigR.Testing.VSHostingProcess/Program.cs

refactor: address code analysis warnings

---

src/ConfigR/Properties/AssemblyInfo.cs

increment to version 0.15.0

---

src/ConfigR/Scripting/ScriptConfigLoader.cs
tests/ConfigR.Features/ConfigR.Features.csproj
tests/ConfigR.Features/EnvironmentallyFriendlyFeature.cs

prevent ConfigR usage from changing the current directory

---

src/ConfigR/Properties/AssemblyInfo.cs

change version from 0.15.0 to 0.14.1

---

src/ConfigR/Properties/AssemblyInfo.cs

incremented minor to 0.15.0

---

tests/ConfigR.Tests.Acceptance/DynamicReferencesFeature.cs

added empty test for in memory assemblies

---

src/ConfigR.Roslyn.CSharp/Internal/Loader.cs
src/ConfigR/Config.cs
src/ConfigR/Sdk/IConfig.cs
tests/ConfigR.Tests.Acceptance.Roslyn.CSharp/LocalConfigurationFeature.cs

implemented LocalConfigurationFeature.PassingAValueFromAnAppToAConfigurationScript

---

tests/ConfigR.Tests.Acceptance.Roslyn.CSharp/AnonymousTypesFeature.cs
tests/ConfigR.Tests.Acceptance.Roslyn.CSharp/ConfigR.Tests.Acceptance.Roslyn.CSharp.csproj
tests/ConfigR.Tests.Acceptance.Roslyn.CSharp/LocalConfigurationFeature.cs
tests/ConfigR.Tests.Acceptance.Roslyn.CSharp/Support/ConfigFile.cs

add more tests for new syntax

---

src/ConfigR.Roslyn.CSharp/ConfigExtensions.cs
src/ConfigR.Roslyn.CSharp/ConfigR.Roslyn.CSharp.csproj
src/ConfigR.Roslyn.CSharp/Guard.cs
src/ConfigR.Roslyn.CSharp/Internal/Loader.cs
src/ConfigR.Roslyn.CSharp/ScriptOptionsExtensions.cs
src/ConfigR.Roslyn.CSharp/packages.config
tests/ConfigR.Tests.Acceptance.Roslyn.CSharp/ConfigR.Tests.Acceptance.Roslyn.CSharp.csproj
tests/ConfigR.Tests.Acceptance.Roslyn.CSharp/DynamicReferencesFeature.cs
tests/ConfigR.Tests.Acceptance.Roslyn.CSharp/packages.config
tests/ConfigR.Tests.Smoke.Service/ConfigR.Tests.Smoke.Service.csproj
tests/ConfigR.Tests.Smoke.Service/packages.config
tests/ConfigR.Tests.Smoke.VSHostingProcess/ConfigR.Tests.Smoke.VSHostingProcess.csproj
tests/ConfigR.Tests.Smoke.VSHostingProcess/packages.config
tests/ConfigR.Tests.Smoke.Website/ConfigR.Tests.Smoke.Website.csproj
tests/ConfigR.Tests.Smoke.Website/packages.config

implemented DynamicReferencesFeature

---

src/ConfigR.Roslyn.CSharp/ConfigExtensions.cs
src/ConfigR.Roslyn.CSharp/Internal/Loader.cs
src/ConfigR.Roslyn.CSharp/ScriptOptionsExtensions.cs
src/ConfigR/DictionaryExtensions.cs
src/ConfigR/Internal/ObjectExtensions.cs
src/ConfigR/Sdk/DynamicDictionary.cs
src/ConfigR/Sdk/IConfig.cs
tests/ConfigR.Tests.Acceptance.Roslyn.CSharp/DictionarySyntaxFeature.cs
tests/ConfigR.Tests.Acceptance.Roslyn.CSharp/DynamicReferencesFeature.cs
tests/ConfigR.Tests.Acceptance.Roslyn.CSharp/EmptyConfigFeature.cs
tests/ConfigR.Tests.Acceptance.Roslyn.CSharp/SearchPathsFeature.cs
tests/ConfigR.Tests.Acceptance.Roslyn.CSharp/StaticTypingFeature.cs
tests/ConfigR.Tests.Smoke.Website/Global.asax.cs
tests/ConfigR.Tests.ruleset

address CA violations

---

src/ConfigR.Roslyn.CSharp/ConfigExtensions.cs
src/ConfigR.Roslyn.CSharp/ConfigR.Roslyn.CSharp.csproj
src/ConfigR.Roslyn.CSharp/Internal/Loader.cs
src/ConfigR.Roslyn.CSharp/Internal/StringExtensions.cs
src/ConfigR.Roslyn.CSharp/ScriptOptionsExtensions.cs
tests/ConfigR.Tests.Smoke.Website/Global.asax.cs
tests/ConfigR.Tests.Smoke.Website/IndexModule.cs
tests/ConfigR.Tests.Smoke.Website/Views/index.sshtml
tests/ConfigR.Tests.Smoke.Website/Web.Debug.csx
tests/ConfigR.Tests.Smoke.Website/Web.Release.csx

treat script path as relative to application base

---

rakefile.rb
src/ConfigR.Roslyn.CSharp/ConfigR.Roslyn.CSharp.nuspec

fix dependencies in ConfigR.Roslyn.CSharp.nuspec

---

rakefile.rb
src/ConfigR.Roslyn.CSharp/ConfigR.Roslyn.CSharp.nuspec

relax dependency on ConfigR to 1.x

---

src/ConfigR/Config.cs
src/ConfigR/Sdk/DynamicDictionary.cs
src/ConfigR/Sdk/IConfig.cs
tests/ConfigR.Tests.Acceptance.Roslyn.CSharp/AnonymousTypesFeature.cs
tests/ConfigR.Tests.Acceptance.Roslyn.CSharp/ConfigR.Tests.Acceptance.Roslyn.CSharp.csproj
tests/ConfigR.Tests.Acceptance.Roslyn.CSharp/DefaultValuesFeature.cs
tests/ConfigR.Tests.Acceptance.Roslyn.CSharp/DynamicReferencesFeature.cs
tests/ConfigR.Tests.Acceptance.Roslyn.CSharp/EmptyConfigFeature.cs
tests/ConfigR.Tests.Acceptance.Roslyn.CSharp/FileConfigurationFeature.cs
tests/ConfigR.Tests.Acceptance.Roslyn.CSharp/LocalConfigurationFeature.cs
tests/ConfigR.Tests.Acceptance.Roslyn.CSharp/MultipleLoadersFeature.cs
tests/ConfigR.Tests.Acceptance.Roslyn.CSharp/SearchPathsFeature.cs
tests/ConfigR.Tests.Acceptance.Roslyn.CSharp/SeedingFeature.cs
tests/ConfigR.Tests.Acceptance.Roslyn.CSharp/StaticTypingFeature.cs
tests/ConfigR.Tests.Acceptance.Roslyn.CSharp/Support/Foo.cs
tests/ConfigR.Tests.Acceptance.Roslyn.CSharp/TypeSyntaxFeature.cs
tests/ConfigR.Tests.Acceptance.Roslyn.CSharp/ValueRetreivalFeature.cs
tests/ConfigR.Tests.Acceptance.Roslyn.CSharp/VisualStudioHostingFeature.cs
tests/ConfigR.Tests.Smoke.Service/ConfigR.Tests.Smoke.Service.exe.csx
tests/ConfigR.Tests.Smoke.Service/Program.cs
tests/ConfigR.Tests.Smoke.VSHostingProcess/Program.cs
tests/ConfigR.Tests.Smoke.Website/Global.asax.cs
tests/ConfigR.Tests.Smoke.Website/IndexModule.cs
tests/ConfigR.Tests.Smoke.Website/Web.Debug.csx
tests/ConfigR.Tests.Smoke.Website/Web.Release.csx

change Load() to LoadDynamic() and type syntax

---

src/ConfigR.Roslyn.CSharp/ConfigR.Roslyn.CSharp.csproj
src/ConfigR.Roslyn.CSharp/Internal/HttpSourceFileResolver.cs
src/ConfigR.Roslyn.CSharp/ScriptOptionsExtensions.cs
tests/ConfigR.Tests.Smoke.Service/ConfigR.Tests.Smoke.Service.exe.csx
tests/ConfigR.Tests.Smoke.Service/Program.cs
tests/ConfigR.Tests.Smoke.Service/Settings.cs

implemented HTTP #load

---

src/ConfigR.Roslyn.CSharp/ConfigExtensions.cs
src/ConfigR.Roslyn.CSharp/ConfigR.Roslyn.CSharp.csproj
src/ConfigR.Roslyn.CSharp/Internal/HttpSourceFileResolver.cs
src/ConfigR.Roslyn.CSharp/Internal/Loader.cs
src/ConfigR.Roslyn.CSharp/Internal/ScriptOptionsExtensions.cs
src/ConfigR.Roslyn.CSharp/Internal/StringExtensions.cs
src/ConfigR.Roslyn.CSharp/ScriptOptionsExtensions.cs
tests/ConfigR.Tests.Smoke.Service/ConfigR.Tests.Smoke.Service.csproj
tests/ConfigR.Tests.Smoke.Service/ConfigR.Tests.Smoke.Service.exe.csx
tests/ConfigR.Tests.Smoke.Service/Program.cs
tests/ConfigR.Tests.Smoke.Service/Settings.cs
tests/ConfigR.Tests.Smoke.Service/Test1.csx
tests/ConfigR.Tests.Smoke.Service/Test2.csx
tests/ConfigR.Tests.Smoke.Service/Test3.csx
tests/ConfigR.Tests.Smoke.VSHostingProcess/Program.cs

implemented loading from path or URI both from app and #load

---

src/ConfigR.Roslyn.CSharp/ConfigR.Roslyn.CSharp.nuspec
src/ConfigR/ConfigR.nuspec

Updated nuspec <iconUrl> to latest logo
